#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)

# Needs to happen first
require "bundler/setup"
require "next_rails"
NextRails::BundleReport::CLI.new(ARGV).run
